name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.7.0
  fpdart: ^1.1.1
  http: ^1.2.2
  get_storage: ^2.1.1
  carousel_slider: ^5.0.0
  lottie: ^3.1.3
  cached_network_image: ^3.4.1
  flutter_html: 3.0.0-beta.2
  webview_flutter: ^4.10.0

  flutter: 
    sdk: flutter
  url_launcher: ^6.3.1

  connectivity_plus: ^6.1.0
  smooth_page_indicator: ^1.2.0+3
  html: ^0.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/icons/
  - assets/animations/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic